# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 272ca28a959980aa76f641c032b4b349c24c08838062a092557298e5e8fd29188f2d973fe0605fd9a192c2c0370c140daa7fe5b159520437f346d5bb9989c872

test:
  secret_key_base: ca68e8d304112cba64b7f17a0c6bc29c40dff74337470336324536c5ccc510bd81b16d0d1b034889ae5a1ec7b03726767ed6c6e930c00f2237fb66a5729098ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
